force-app/main/default/objects/Approval_Process_Node_To_Queue_Mapping__mdt/Approval_Process_Node_To_Queue_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Approval Process Node To Queue Mapping</label>
    <pluralLabel>Approval Process Node To Queue Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Approval_Process_Node_To_Queue_Mapping__mdt/fields/Approval_Process_Node__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Node__c</fullName>
    <label>Approval Process Node</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Process_Node_To_Queue_Mapping__mdt/fields/Replacement_Queue__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Queue__c</fullName>
    <label>Replacement Queue</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PNNL_ApprovalProcessUpdateToQueueHandler.cls
public with sharing class PNNL_ApprovalProcessUpdateToQueueHandler {
    public PNNL_ApprovalProcessUpdateToQueueHandler() {

    }

    @InvocableMethod
    public static void UpdateApprovalProcessesForObject(List<Id> tmpObjectIDs) {
        List<Approval_Process_Node_To_Queue_Mapping__mdt> queueMappings = [
                SELECT 
                    Label, 
                    DeveloperName, 
                    Approval_Process_Node__c, 
                    Replacement_Queue__c 
                FROM Approval_Process_Node_To_Queue_Mapping__mdt
            ] ;

        System.Debug('***queueMappings: ' + queueMappings) ;

        List<ProcessInstance> processInstanceList = [
                SELECT 
                    ID, 
                    CompletedDate, 
                    ElapsedTimeInDays, 
                    ElapsedTimeInHours,
                    ElapsedTimeInMinutes, 
                    LastActorId, 
                    Status, 
                    ProcessDefinition.Name, 
                    TargetObjectId 
                FROM ProcessInstance 
                WHERE TargetObjectId = :tmpObjectIDs
            ] ;
        System.Debug('***processInstanceList: ' + processInstanceList) ;
    }
}