force-app/main/default/objects/Budget_Reporting_Code__c/Budget_Reporting_Code__c.object-meta.xml
<CustomObject>
    <label>Budget &amp; Reporting Code</label>
    <nameField>
        <label>Budget &amp; Reporting Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget &amp; Reporting Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Reporting_Code__c/fields/Number_of_B_R_Entries__c.field-meta.xml
<CustomField>
    <fullName>Number_of_B_R_Entries__c</fullName>
    <label>Number of B &amp; R Entries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PNNL_PreventBudgetCodeDeletionTest.cls
@isTest
private class PNNL_PreventBudgetCodeDeletionTest {
    @TestSetup
    static void loadData() {
        //  Create Budget Reporting Code entry
        Budget_Reporting_Code__c brc = new Budget_Reporting_Code__c();
        brc.Name = '123456';
        brc.Number_of_B_R_Entries__c = 1;
        insert brc;
    }
    @isTest
    static void testBRCDelete(){
        try{ 
            Budget_Reporting_Code__c brc = [select id from Budget_Reporting_Code__c limit 1];
            delete brc;            
        }Catch (DMLException e){
            System.assert(e.getMessage().contains('This record cannot be deleted'), 'This record cannot be deleted');
        }
    }
    
}