force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>An attachments object to replace the standard attachments object in Salesforce, to allow for attachment types.</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Funding_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT Agreement</fullName>
            </value>
            <value>
                <fullName>Animal Use – SC Response</fullName>
            </value>
            <value>
                <fullName>Animal Use Worksheet</fullName>
            </value>
            <value>
                <fullName>Biographical sketches</fullName>
            </value>
            <value>
                <fullName>CI Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Client Certification (hard gate)</fullName>
            </value>
            <value>
                <fullName>DOE Approved Proposal</fullName>
            </value>
            <value>
                <fullName>HQ Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Incoming WAS Email from PNSO</fullName>
            </value>
            <value>
                <fullName>IP Management Plan</fullName>
            </value>
            <value>
                <fullName>IWO Funding Document (hard gate)</fullName>
            </value>
            <value>
                <fullName>MSOF</fullName>
            </value>
            <value>
                <fullName>NF-SPP Agreement</fullName>
            </value>
            <value>
                <fullName>Obligation Cost Roadmap</fullName>
            </value>
            <value>
                <fullName>OCI Addendum</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Letter</fullName>
            </value>
            <value>
                <fullName>PSO Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Research Plan</fullName>
            </value>
            <value>
                <fullName>SC Analysis Worksheet</fullName>
            </value>
            <value>
                <fullName>SC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Sponsor Registration</fullName>
            </value>
            <value>
                <fullName>SPP Justification</fullName>
            </value>
            <value>
                <fullName>Statement of Work (hard gate)</fullName>
            </value>
            <value>
                <fullName>Sub-contract Plan</fullName>
            </value>
            <value>
                <fullName>TPEC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Work Authorization Document</fullName>
            </value>
            <value>
                <fullName>Animal Use -SC Response</fullName>
                <isActive>false</isActive>
                <label>Animal Use -SC Response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>AttachmentId__c</fullName>
    <description>The Id of the attachment.</description>
    <inlineHelpText>The Id of the attachment.</inlineHelpText>
    <label>AttachmentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <label>Funding Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>CRADA</fullName>
            </value>
            <value>
                <fullName>DHS</fullName>
            </value>
            <value>
                <fullName>F-SPP</fullName>
            </value>
            <value>
                <fullName>IWO</fullName>
            </value>
            <value>
                <fullName>NF-SPP</fullName>
            </value>
            <value>
                <fullName>NIC-RW</fullName>
            </value>
            <value>
                <fullName>SIPP</fullName>
            </value>
            <value>
                <fullName>DOE Direct</fullName>
            </value>
            <value>
                <fullName>FIN Plan Proposal</fullName>
                <isActive>false</isActive>
                <label>FIN Plan Proposal</label>
            </value>
            <value>
                <fullName>Field Work Proposal</fullName>
                <isActive>false</isActive>
                <label>Field Work Proposal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PNNL_CopyAttachment.cls
public class PNNL_CopyAttachment {
  public static string clonedOppty;

  @InvocableMethod
  public static void CopyAttachment(List<List<Id>> opptyIds) {
    clone_opptyAttachments(opptyIds);
  }

  public static void clone_opptyAttachments(List<List<Id>> opptyIds) {
    //System.debug('Original Opty: ' + opptyIds[0][0]);
    string opptyId = opptyIds[0][0];
    //System.debug('Cloned Opty: ' + opptyIds[0][1]);
    string clonedOppty = opptyIds[0][1];
    Set<Id> ContentDocumentIds = new Set<Id>();
    ContentDocumentLink[] cdls = new List<ContentDocumentLink>();
    List<Opportunity_Attachment__c> attchList = new List<Opportunity_Attachment__c>();

    Map<Id, Opportunity_Attachment__c> oppAttachItems = new Map<Id, Opportunity_Attachment__c>(
      [
        SELECT
          Id,
          Name,
          Funding_Type__c,
          Attachment_Type__c,
          RecordTypeId,
          Opportunity__c,
          AttachmentId__c
        FROM Opportunity_Attachment__c
        WHERE Opportunity__c = :opptyId
      ]
    );

    if (oppAttachItems.isEmpty()) {
      //System.debug('No Attachments to copy.');
      return;
    }

    // loop at the attachment list and place content document records in a list
    for (Opportunity_Attachment__c attachmentRecord : oppAttachItems.values()) {
      //System.debug('Attachment Id is : ' + attachmentRecord.AttachmentId__c);
      ContentDocumentIds.add(attachmentRecord.AttachmentId__c);
    }
    //System.debug('ContentDocumentIds: ' + ContentDocumentIds);
    Map<Id, ContentVersion> versionItem = new Map<Id, ContentVersion>(
      [
        SELECT fields(standard)
        FROM ContentVersion
        WHERE
          IsLatest = TRUE
          AND IsDeleted = FALSE
          AND ContentDocumentId IN :ContentDocumentIds
      ]
    );

    if (versionItem.isEmpty()) {
      //System.debug('No Content Version Records found for the attachment file.');
      return;
    }

    //debugging only
    /*
System.debug('Looping through the content version Map');
for (Id cvId : versionItem.keySet()){
System.debug('version record: '+ versionItem.get(cvId));
}
*/

    for (Opportunity_Attachment__c attachment : oppAttachItems.values()) {
      //	Clone Attachment Record
      Opportunity_Attachment__c oppAttachClone = attachment.clone(
        false,
        true,
        false,
        false
      );
      oppAttachClone.Opportunity__c = clonedOppty;
      attchList.add(oppAttachClone);
    }
    // insert the list of attachment records
    insert attchList;

    //loop over newly created attachments and update the attachment_id field
    for (Opportunity_Attachment__c attachment : attchList) {
      //System.debug('ContentDocumentIds: ' + ContentDocumentIds);
      //loop over version records to find the one where contentdocumentid = attachmentId__c
      //
      for (ContentVersion cv : versionItem.values()) {
        //System.debug('version record: ' + cv);
        if (cv.contentdocumentid == attachment.AttachmentId__c) {
          //found the record.
          //
          ContentVersion versionNew = new ContentVersion(
            VersionData = cv.VersionData,
            Title = cv.Title,
            ContentUrl = cv.ContentUrl,
            PathOnClient = cv.PathOnClient
          );
          insert versionNew;
          //System.debug('Number of DML statements used so far : ' + Limits.getDmlStatements());
          //system.debug('VersionNew Id value: ' + versionNew.Id);
          ContentVersion versionNewQueried = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id = :versionNew.Id
            LIMIT 1
          ];
          cdls.add(
            new ContentDocumentLink(
              LinkedEntityId = attachment.Id,
              ContentDocumentId = versionNewQueried.ContentDocumentId
            )
          );
          attachment.AttachmentId__c = versionNewQueried.ContentDocumentId;
          //break out of the loop
          break;
        }
      }
    }
    //update the attachment list with new content document id ids
    update attchList;
    //insert the document link items to associate the new file to the opportunity
    insert cdls;

    //for debugging only
    /*  
* for (ContentDocumentLink cdl : docLinkItems){
system.debug('The original doclinkedItems:');
system.debug(cdl);
}

for (Opportunity_Attachment__c newCloneAttachment: [select id, name from Opportunity_Attachment__c where id IN :attchList]){
system.debug('This is the new list of attachments: '+ newCloneAttachment);
}

for (ContentVersion cv: versionItem){
system.debug('Looping through the contentversion records: '+cv);
}

    System.debug(
      'Final number of script statements used : ' + Limits.getDmlStatements()
    );
    System.debug('Heap size Limit: ' + Limits.getLimitHeapSize());
    System.debug('Final heap size: ' + Limits.getHeapSize());
    System.debug('Number of Queries used in this apex code so far: ' + Limits.getQueries());
*/
  }
}