force-app/main/default/objects/Opportunity/recordTypes/ACT.recordType-meta.xml
<RecordType>
    <fullName>ACT</fullName>
    <active>true</active>
    <businessProcess>Non-DOE Sales Process</businessProcess>
    <description>Agreements for Commercializing Technology</description>
    <label>ACT</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <businessProcess>CRADA%2FJA%2FOther</businessProcess>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>An attachments object to replace the standard attachments object in Salesforce, to allow for attachment types.</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Funding_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT Agreement</fullName>
            </value>
            <value>
                <fullName>Animal Use – SC Response</fullName>
            </value>
            <value>
                <fullName>Animal Use Worksheet</fullName>
            </value>
            <value>
                <fullName>Biographical sketches</fullName>
            </value>
            <value>
                <fullName>CI Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Client Certification (hard gate)</fullName>
            </value>
            <value>
                <fullName>DOE Approved Proposal</fullName>
            </value>
            <value>
                <fullName>HQ Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Incoming WAS Email from PNSO</fullName>
            </value>
            <value>
                <fullName>IP Management Plan</fullName>
            </value>
            <value>
                <fullName>IWO Funding Document (hard gate)</fullName>
            </value>
            <value>
                <fullName>MSOF</fullName>
            </value>
            <value>
                <fullName>NF-SPP Agreement</fullName>
            </value>
            <value>
                <fullName>Obligation Cost Roadmap</fullName>
            </value>
            <value>
                <fullName>OCI Addendum</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Letter</fullName>
            </value>
            <value>
                <fullName>PSO Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Research Plan</fullName>
            </value>
            <value>
                <fullName>SC Analysis Worksheet</fullName>
            </value>
            <value>
                <fullName>SC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Sponsor Registration</fullName>
            </value>
            <value>
                <fullName>SPP Justification</fullName>
            </value>
            <value>
                <fullName>Statement of Work (hard gate)</fullName>
            </value>
            <value>
                <fullName>Sub-contract Plan</fullName>
            </value>
            <value>
                <fullName>TPEC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Work Authorization Document</fullName>
            </value>
            <value>
                <fullName>Animal Use -SC Response</fullName>
                <isActive>false</isActive>
                <label>Animal Use -SC Response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>AttachmentId__c</fullName>
    <description>The Id of the attachment.</description>
    <inlineHelpText>The Id of the attachment.</inlineHelpText>
    <label>AttachmentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <label>Funding Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>CRADA</fullName>
            </value>
            <value>
                <fullName>DHS</fullName>
            </value>
            <value>
                <fullName>F-SPP</fullName>
            </value>
            <value>
                <fullName>IWO</fullName>
            </value>
            <value>
                <fullName>NF-SPP</fullName>
            </value>
            <value>
                <fullName>NIC-RW</fullName>
            </value>
            <value>
                <fullName>SIPP</fullName>
            </value>
            <value>
                <fullName>DOE Direct</fullName>
            </value>
            <value>
                <fullName>FIN Plan Proposal</fullName>
                <isActive>false</isActive>
                <label>FIN Plan Proposal</label>
            </value>
            <value>
                <fullName>Field Work Proposal</fullName>
                <isActive>false</isActive>
                <label>Field Work Proposal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PNNL_UploadAttachmentController.cls
public class PNNL_UploadAttachmentController {
  private Opportunity opportunity { get; set; }
  public String fileName { get; set; }
  public Blob fileBody { get; set; }
  public boolean testExceptionValidation = false;

  public PNNL_UploadAttachmentController(
    ApexPages.StandardController controller
  ) {
    this.opportunity = (Opportunity) controller.getRecord();
  }

  // creates a new Opportunity_Attachment__c record
  @testVisible
  private Database.SaveResult saveCustomAttachment() {
    Opportunity_Attachment__c obj = new Opportunity_Attachment__c();
    obj.opportunity__c = opportunity.Id;
    if (test.isRunningTest()) {
      obj.Funding_Type__c = 'ACT';
      obj.Attachment_Type__c = 'Other';
    }
    return Database.insert(obj);
  }

  // create an actual Attachment record with the Opportunity_Attachment__c as parent
  //private Database.SaveResult saveStandardAttachment(Id parentId) {
  @testVisible
  private Database.SaveResult saveStandardAttachment(Id parentId) {
    Database.SaveResult result;

    Attachment attachment = new Attachment();
    attachment.body = (test.isRunningTest())
      ? blob.valueof('testbody')
      : this.fileBody;
    attachment.name = (test.isRunningTest()) ? 'testname' : this.fileName;
    attachment.parentId = parentId;
    // insert the attachment
    result = Database.insert(attachment);
    // reset the file for the view state
    fileBody = Blob.valueOf(' ');
    return result;
  }

  private boolean handleError(database.SaveResult dbsr) {
    boolean returnValue = false;
    if (dbsr == null || !dbsr.isSuccess() || testExceptionValidation == true) {
      ApexPages.AddMessage(
        new ApexPages.Message(
          ApexPages.Severity.ERROR,
          'Could not save attachment.'
        )
      );
      returnValue = true;
    }
    return returnValue;
  }
  
  /**
   * Upload process is:
   *  1. Insert new Opportunity_Attachment__c record
   *  2. Insert new Attachment with the new Opportunity_Attachment__c record as parent
   *  3. Update the Opportunity_Attachment__c record with the ID of the new Attachment
   **/
  public PageReference processUpload() {
    try {
      Database.SaveResult customAttachmentResult = saveCustomAttachment();
      if (handleError(customAttachmentResult)) {
        return null;
      }
      Database.SaveResult attachmentResult = saveStandardAttachment(
        customAttachmentResult.getId()
      );
      if (handleError(attachmentResult)) {
        return null;
      } else {
        /*if (attachmentResult == null || !attachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                  'Could not save attachment.'));            
                return null;*/
        // update the custom attachment record with some attachment info
        Opportunity_Attachment__c customAttachment = [
          SELECT id
          FROM Opportunity_Attachment__c
          WHERE id = :customAttachmentResult.getId()
        ];
        customAttachment.name = this.fileName;
        customAttachment.AttachmentId__c = attachmentResult.getId();
        update customAttachment;
      }
    } catch (Exception e) {
      ApexPages.AddMessages(e);
      System.debug(e.getMessage());
      return null;
    }

    return new PageReference('/' + opportunity.Id);
  }

  public PageReference back() {
    return new PageReference('/' + opportunity.Id);
  }
}