force-app/main/default/objects/Opportunity/fields/Contract_Client__c.field-meta.xml
<CustomField>
    <fullName>Contract_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Client</relationshipLabel>
    <relationshipName>Contract_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Funding_Client__c.field-meta.xml
<CustomField>
    <fullName>Funding_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Funding Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Client</relationshipLabel>
    <relationshipName>Funding_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/ACT.recordType-meta.xml
<RecordType>
    <fullName>ACT</fullName>
    <active>true</active>
    <businessProcess>Non-DOE Sales Process</businessProcess>
    <description>Agreements for Commercializing Technology</description>
    <label>ACT</label>
</RecordType>

force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>An attachments object to replace the standard attachments object in Salesforce, to allow for attachment types.</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Funding_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT Agreement</fullName>
            </value>
            <value>
                <fullName>Animal Use – SC Response</fullName>
            </value>
            <value>
                <fullName>Animal Use Worksheet</fullName>
            </value>
            <value>
                <fullName>Biographical sketches</fullName>
            </value>
            <value>
                <fullName>CI Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Client Certification (hard gate)</fullName>
            </value>
            <value>
                <fullName>DOE Approved Proposal</fullName>
            </value>
            <value>
                <fullName>HQ Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Incoming WAS Email from PNSO</fullName>
            </value>
            <value>
                <fullName>IP Management Plan</fullName>
            </value>
            <value>
                <fullName>IWO Funding Document (hard gate)</fullName>
            </value>
            <value>
                <fullName>MSOF</fullName>
            </value>
            <value>
                <fullName>NF-SPP Agreement</fullName>
            </value>
            <value>
                <fullName>Obligation Cost Roadmap</fullName>
            </value>
            <value>
                <fullName>OCI Addendum</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Letter</fullName>
            </value>
            <value>
                <fullName>PSO Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Research Plan</fullName>
            </value>
            <value>
                <fullName>SC Analysis Worksheet</fullName>
            </value>
            <value>
                <fullName>SC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Sponsor Registration</fullName>
            </value>
            <value>
                <fullName>SPP Justification</fullName>
            </value>
            <value>
                <fullName>Statement of Work (hard gate)</fullName>
            </value>
            <value>
                <fullName>Sub-contract Plan</fullName>
            </value>
            <value>
                <fullName>TPEC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Work Authorization Document</fullName>
            </value>
            <value>
                <fullName>Animal Use -SC Response</fullName>
                <isActive>false</isActive>
                <label>Animal Use -SC Response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>AttachmentId__c</fullName>
    <description>The Id of the attachment.</description>
    <inlineHelpText>The Id of the attachment.</inlineHelpText>
    <label>AttachmentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <label>Funding Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>CRADA</fullName>
            </value>
            <value>
                <fullName>DHS</fullName>
            </value>
            <value>
                <fullName>F-SPP</fullName>
            </value>
            <value>
                <fullName>IWO</fullName>
            </value>
            <value>
                <fullName>NF-SPP</fullName>
            </value>
            <value>
                <fullName>NIC-RW</fullName>
            </value>
            <value>
                <fullName>SIPP</fullName>
            </value>
            <value>
                <fullName>DOE Direct</fullName>
            </value>
            <value>
                <fullName>FIN Plan Proposal</fullName>
                <isActive>false</isActive>
                <label>FIN Plan Proposal</label>
            </value>
            <value>
                <fullName>Field Work Proposal</fullName>
                <isActive>false</isActive>
                <label>Field Work Proposal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PNNL_CopyAttachmentTest.cls
@isTest
private class PNNL_CopyAttachmentTest {
  static Map<Id, Opportunity> insertedOpportunities;
  static Map<Id, Opportunity_Attachment__c> attachments;
  static Map<Id, ContentVersion> contentVersions;

  @TestSetup
  static void loadData() {
    //  Create Account
    Id accountId = createAccount();

    //  Create Opportunity to Add Opp Line Items
    Id opportunityId = createOpportunity(accountId);
    system.debug(opportunityId);
    Id duplicateOpportunityId = createOpportunity(accountId);
    system.debug(duplicateOpportunityId);
    //  Create Opportunity Attachment
    Id attachmentId = createOpportunityAttachment(opportunityId);

    // Create ContentVersion Record
    Id contentVersion = createContentVersion();

    // Create Document Link Record
    Id docLinkRecord = createDocumentLink(attachmentId, contentVersion);
  }

  public static Id createAccount() {
    Account accountRec = new Account();
    accountRec.Name = 'Account Test Class Record ';
    insert accountRec;
    return accountRec.Id;
  }

  public static Id createOpportunity(Id accountId) {
    final String OPP_REC_NAME =
      'Test Record Name - ' + String.valueOf(getRandomNum(9999));
    final String OPP_REC_TYPE_ACT_NAME = 'ACT';
    final String OPP_STAGE_NAME = 'Scope Filled';
    final Date CloseDate = Date.today() + 30;

    Opportunity oppRec = new Opportunity();
    oppRec.Name = OPP_REC_NAME;
    oppRec.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
      .get(OPP_REC_TYPE_ACT_NAME)
      .getRecordTypeId();
    oppRec.StageName = OPP_STAGE_NAME;
    oppRec.CloseDate = CloseDate;
    oppRec.Contract_Client__c = accountId;
    oppRec.Funding_Client__c = accountId;
    insert oppRec;

    return oppRec.Id;
  }

  public static Id createOpportunityAttachment(Id opportunityId) {
    Opportunity_Attachment__c oppAttachment = new Opportunity_Attachment__c();
    oppAttachment.Name = 'My New Attachment';
    oppAttachment.Attachment_Type__c = 'ACT Agreement';
    oppAttachment.Funding_Type__c = 'ACT';
    oppAttachment.Opportunity__c = opportunityId;
    insert oppAttachment;
    return oppAttachment.Id;
  }

  public static Id createContentVersion() {
    ContentVersion cvItem = new ContentVersion();
    cvItem.Title = 'ContentTest';
    cvItem.PathOnClient = 'TestforDocuementClone';
    cvItem.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');
    insert cvItem;
    return cvItem.Id;
  }

  public static Id createDocumentLink(Id oppAttachment, Id cvItem) {
    ContentVersion versionNewQueried = [
      SELECT ContentDocumentId
      FROM ContentVersion
      WHERE Id = :cvItem
      LIMIT 1
    ];
    ContentDocumentLink docLinkNew = new ContentDocumentLink(
      LinkedEntityId = oppAttachment,
      ContentDocumentId = versionNewQueried.ContentDocumentId
    );
    Opportunity_Attachment__c opAttach = new Opportunity_Attachment__c(
      Id = oppAttachment,
      AttachmentId__c = versionNewQueried.ContentDocumentId
    );
    update opAttach;
    insert docLinkNew;
    return docLinkNew.Id;
  }

  private static Integer getRandomNum(Integer maxNum) {
    Integer retRandom = Integer.valueof((Math.random() * maxNum));
    return retRandom;
  }

  static void getIds() {
    insertedOpportunities = new Map<Id, Opportunity>(
      [SELECT Id, Name FROM Opportunity]
    );
    attachments = new Map<Id, Opportunity_Attachment__c>(
      [SELECT Id, Name FROM Opportunity_Attachment__c]
    );
    contentVersions = new Map<Id, ContentVersion>(
      [SELECT Id, Title FROM ContentVersion]
    );

    for (Opportunity opp : insertedOpportunities.values()) {
      System.debug(
        'Opportunity Id :' +
        opp.Id +
        ' ' +
        'Opportunity Name : ' +
        opp.Name
      );
    }
  }
  //after calling the invocable method CopyAttachment, the new opportunity id should have a
  //the same number of attachments and links as the original
  //
  //
  @isTest
  static void testAttachmentCopy() {
    system.debug([SELECT id FROM opportunity].size());
    List<List<Id>> listOfIds = new List<List<Id>>();
    List<Id> listToAdd = new List<Id>();
    getIds();
    for (Opportunity opp : insertedOpportunities.values()) {
      System.debug(
        'Opportunity Id :' +
        opp.Id +
        ' ' +
        'Opportunity Name : ' +
        opp.Name
      );
      listToAdd.add(opp.Id);
    }

    listOfIds.add(listToAdd);

    PNNL_CopyAttachment.CopyAttachment(listOfIds);
    getIds();

    System.assertEquals(2, insertedOpportunities.Size());

    System.assertEquals(2, attachments.Size());

    System.assertEquals(2, contentVersions.size());

    // check the links
    List<Id> checkLinkItems = new List<Id>();
    for (Opportunity_Attachment__c attachment : attachments.values()) {
      List<ContentDocumentLink> docLinkItems = [
        SELECT Id, LinkedEntityId, ContentDocumentId
        FROM ContentDocumentLink
        WHERE LinkedEntityId = :attachment.Id
      ];
      checkLinkItems.add(docLinkItems[0].Id);
    }

    System.assertEquals(2, checkLinkItems.size());
  }
}