force-app/main/default/objects/Opportunity/fields/Contract_Client__c.field-meta.xml
<CustomField>
    <fullName>Contract_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Client</relationshipLabel>
    <relationshipName>Contract_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Funding_Client__c.field-meta.xml
<CustomField>
    <fullName>Funding_Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Funding Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funding Client</relationshipLabel>
    <relationshipName>Funding_Client</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <businessProcess>CRADA%2FJA%2FOther</businessProcess>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Opportunity_Attachment__c/Opportunity_Attachment__c.object-meta.xml
<CustomObject>
    <description>An attachments object to replace the standard attachments object in Salesforce, to allow for attachment types.</description>
    <label>Attachment</label>
    <nameField>
        <label>Attachments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Funding_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT Agreement</fullName>
            </value>
            <value>
                <fullName>Animal Use – SC Response</fullName>
            </value>
            <value>
                <fullName>Animal Use Worksheet</fullName>
            </value>
            <value>
                <fullName>Biographical sketches</fullName>
            </value>
            <value>
                <fullName>CI Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Client Certification (hard gate)</fullName>
            </value>
            <value>
                <fullName>DOE Approved Proposal</fullName>
            </value>
            <value>
                <fullName>HQ Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Incoming WAS Email from PNSO</fullName>
            </value>
            <value>
                <fullName>IP Management Plan</fullName>
            </value>
            <value>
                <fullName>IWO Funding Document (hard gate)</fullName>
            </value>
            <value>
                <fullName>MSOF</fullName>
            </value>
            <value>
                <fullName>NF-SPP Agreement</fullName>
            </value>
            <value>
                <fullName>Obligation Cost Roadmap</fullName>
            </value>
            <value>
                <fullName>OCI Addendum</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Proposal Letter</fullName>
            </value>
            <value>
                <fullName>PSO Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Research Plan</fullName>
            </value>
            <value>
                <fullName>SC Analysis Worksheet</fullName>
            </value>
            <value>
                <fullName>SC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Sponsor Registration</fullName>
            </value>
            <value>
                <fullName>SPP Justification</fullName>
            </value>
            <value>
                <fullName>Statement of Work (hard gate)</fullName>
            </value>
            <value>
                <fullName>Sub-contract Plan</fullName>
            </value>
            <value>
                <fullName>TPEC Foreign Approval</fullName>
            </value>
            <value>
                <fullName>Work Authorization Document</fullName>
            </value>
            <value>
                <fullName>Animal Use -SC Response</fullName>
                <isActive>false</isActive>
                <label>Animal Use -SC Response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <label>Funding Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>CRADA</fullName>
            </value>
            <value>
                <fullName>DHS</fullName>
            </value>
            <value>
                <fullName>F-SPP</fullName>
            </value>
            <value>
                <fullName>IWO</fullName>
            </value>
            <value>
                <fullName>NF-SPP</fullName>
            </value>
            <value>
                <fullName>NIC-RW</fullName>
            </value>
            <value>
                <fullName>SIPP</fullName>
            </value>
            <value>
                <fullName>DOE Direct</fullName>
            </value>
            <value>
                <fullName>FIN Plan Proposal</fullName>
                <isActive>false</isActive>
                <label>FIN Plan Proposal</label>
            </value>
            <value>
                <fullName>Field Work Proposal</fullName>
                <isActive>false</isActive>
                <label>Field Work Proposal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Attachment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UploadAttachmentControllerTest.cls
@isTest
public class UploadAttachmentControllerTest {
    
    @testSetup
    static void setup(){
        Account acc = new Account(name='test');
        insert acc;
        Opportunity opp = new Opportunity(Name='test',StageName='Scope Cleared',CloseDate = Date.today(), Contract_Client__c=acc.Id, Funding_Client__c=acc.Id,accountId=acc.Id);
        insert opp;
        Opportunity_Attachment__c OppA = new Opportunity_Attachment__c(Funding_Type__c='FIN Plan Proposal',Attachment_Type__c='Other',Opportunity__c=opp.Id);
        insert OppA;
    }
 
    static testmethod void testCase1(){
		List<Opportunity> Opps = [SELECT Name,StageName,CloseDate,Contract_Client__c,Funding_Client__c,accountId 
                           FROM Opportunity 
                           WHERE Name=:'test' LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opps[0]);
        UploadAttachmentController controller = new UploadAttachmentController(sc);
        
        
        test.startTest();
          controller.processUpload();
          controller.saveStandardAttachment(opps[0].id);
        test.stopTest();
    }    
    static testmethod void testCase2(){
		List<Opportunity> Opps = [SELECT Name,StageName,CloseDate,Contract_Client__c,Funding_Client__c,accountId 
                           FROM Opportunity 
                           WHERE Name=:'test' LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opps[0]);
        UploadAttachmentController controller = new UploadAttachmentController(sc);
        controller.testExceptionValidation = true;
        
        test.startTest();
          controller.processUpload();
          //controller.saveStandardAttachment(opps[0].id);
        test.stopTest();
    }    
}